### ISSUE TITLE
Where is library.yml?

### ISSUE THREAD

**Issue by 3togo** [mess42/pyrate#109]
in line60 of material_glasscat.py, it mentioned a file named "library.yml" but where is it? 
self.librarydict = self.read_library(database_basepath + "/library.yml")

**Comment by joha2** [comment]
Hey @3togo you will get the material library if you update the submodules such that you get an up-to-date version of refractive-index.info. This is what library.yml is about. Do you have any suggestions about a better implementation than via a hard coded path?

Best wishes
Johannes

**Comment by 3togo** [comment]
I got it.  Just overlook the need to pull submodules s well
git pull --recurse-submodules
