### ISSUE TITLE
py3 compatible?

### ISSUE THREAD

**Issue by luzpaz** [mess42/pyrate#112]
Pyrate is listed as an addon for the [FreeCAD addon manager](https://github.com/FreeCAD/FreeCAD-addons) 
in the upcoming end of the year release FreeCAD will release version 0.18 that should be fully py3 and Qt5 compatible. Please keep us in the loop about pyrate as well. Thank you kindly!
 
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
@joha2 good question. Please direct that to the FC community esp. @looooo

**Comment by joha2** [comment]
to be merged.
