### ISSUE TITLE
Proposal for a new icon that represent pyrate in FreeCAD

### ISSUE THREAD

**Issue by luzpaz** [mess42/pyrate#115]
![image](https://user-images.githubusercontent.com/4140247/46435704-fc460f00-c724-11e8-9d2f-48b06e3e1328.png)
ref: https://forum.freecadweb.org/viewtopic.php?f=34&t=31289

CC @joha2 
FYI, icon has been converted to SVG in the FC forum as well. Props go to @AR795

**Comment by joha2** [comment]
@luzpaz thanks for bringing this forum thread to my attention. The icons are very nice. I just phoned to @mess42 and of the icons will be chosen to substitute ours.

Best wishes
Johannes

**Comment by luzpaz** [comment]
@joha2 :+1: 

For continuity of the thread here are the other icons revisions by @AR795
![image](https://user-images.githubusercontent.com/4140247/46556990-5e824980-c8b6-11e8-8255-a2b29096679f.png)
![image](https://user-images.githubusercontent.com/4140247/46556994-63df9400-c8b6-11e8-8c0b-4fdba95fa73e.png)

**Comment by joha2** [comment]
@luzpaz thanks for providing these further icons on github! I think one of the last two icons is likely to be selected very soon to substitute ours. :-)

**Comment by joha2** [comment]
We selected one for the workbench, thanks so much!
