### ISSUE TITLE
How could I simulate an extended source such as a slit?

### ISSUE THREAD

**Issue by calocedrus** [mess42/pyrate#131]
Hello,

First, congratulations to the pyrate team on the work done, this is impressive and very motivating. 
I would like to obtain the image of an extended source seen through a lens, is it possible, and if so where should I dig to do so?
One way to do it would be to add an aperture along the rays path, an aperture with the shape / dimensions of the extended source, is it possible?

**Comment by calocedrus** [comment]
I may have found some hints in `pyrateoptics/sampling2d/raster.py`, I'd need to define a proper rectangular grid with a raster of my choice. 
Am I on the right track?
 I'd also need to be able to relate the aperture dimension to real size (e.g. 100um wide by 6mm long).

**Comment by joha2** [comment]
I am not an extended light source expert: A first location to dig is to manually define a raybundle with several x, k, and E vectors. If it is correct that an extended light source can be modelled by overlapping point sources, then the I would suggest to create several 1000 x per point source using k vectors in a spherical shape around them. But notice: you have to define the correct E field(-direction), the direction vector of the rays is calculated from the Poynting vector! When you trace the raybundle, you could truncate the beam footprint by using a slit-type rectangular aperture.

The raster is maybe also something to consider: It is thought to create a raster between -1, 1 for x, y to provide a convenient way for pupil and field sampling, but you can also use it to generate a raybundle. But there is no proper API for that. And, I am not sure whether just 1000 rays coming from a rectangular aperture in a regular grid, are able to model an extend light source. I would think that the direction of the rays has to be stochastic. But as I said, I am not an expert at all on that :-)
