### ISSUE TITLE
Newbie Questions

### ISSUE THREAD

**Issue by Chris-A13** [mess42/pyrate#154]
Hello Mess42,

I was going through the Wiki page and you mention that their is a fundamental manual for Pyrate but I can't find it in the code section or in the Wiki. I was just wondering if you would be able to point me in the right direction.

Also, does Pyrate run through FreeCAD in the python console section down below or do I write the code in Idle or Pycharm and upload the code?

Regards,
Chris

**Comment by joha2** [comment]
Hello @Chris-A13 

I hope it is OK, if I answer on behalf of Mess42. You can obtain the manual by downloading or cloning the repo and going into the directory `doc` which contains a sub dictory `rtfm`. There exists a bunch of `.tex` files which you can compile with your favorite LaTeX system (usually `pdflatex`). Afterwards there should be a `pdf` file of the documentation.

About your second question: Pyrate can run in any Python environment which provides at least scipy and numpy. Therefore it can be used in some special FreeCAD flavors (there exist some with scipy, some without) as well as within e.g. an Anaconda environment.

Hope this helps!

Best wishes
Johannes

**Comment by Chris-A13** [comment]
Hello @ joha2,

Yes that is perfect, thank you very much.
The service here is fantastic!!

Regards,
Chris
