### ISSUE TITLE
Pyrate capabilities

### ISSUE THREAD

**Issue by Chris-A13** [mess42/pyrate#157]
Hello everyone,

I have been playing with Pyrate for a few weeks now as I am currently undertaking my honours project at university and I'm trying to build a software package for a local company. The package will be a dual mirrored optical system with a source coming into an OAP mirror which is constant but has the ability to change the second mirror in the system.

Pyrate has been brilliant for 2D analysis, so thank you very much and awesome work so far. I was wondering if it is capable for 3D analysis? I've been going through your demos to try and teach myself how everything works as I am pretty new to Python while also being new to optics analysis, but all the demos only show 2D visualisation of the code you have supplied.

I was also wondering what shapes are available in the analysis? as I am currently just using the conic with a curv of zero so that all my mirrors are basic planar mirrors.

Any help with this would be greatly appreciated,
Chris

**Comment by joha2** [comment]
Dear @Chris-A13 

Thank you for using pyrate! We really appreciate that our software is actually used. At the end of your project it would be nice to reference to it in our wiki. If it is possible, could you please provide a link to it or to your thesis/report?

To your question: Pyrate was created with full asymmetric 3D optical designs in mind. Therefore, 3D analysis are possible, but at the moment the visualization is quite elementary. However, there is a demo file where we demonstrated how to show slider elements in the matplotlib window to rotate the optical system in the plot (See line 120 in https://github.com/mess42/pyrate/blob/master/demos/demo_anisotropic_doublet.py). We also planned to use FreeCAD as an 3D interface, but progress is blocked by other issues. But from a software point of view you have full control over the 3D coordinate systems and the shapes and apertures of the system.

Further, there are many more surface shapes available (see the classes in https://github.com/mess42/pyrate/blob/master/pyrateoptics/raytracer/surface_shape.py). There are polynomial aspheres, XY polynomials, Zernike Fringe, to name just a few. The Conic shape itself can have a radius of curvature and a conic constant to model spheres (cc=0), elliptical mirrors (cc<-1), hyperbolic mirrors (cc>-1), or parabolas (cc=-1) (all rotationally symmetric around the local z axis). A word of caution: Please be aware that the interface of these classes is not settled, yet and may be change anytime without notice. (E.g. I am not very happy with the lists to provide for the aspheric or Zernike coefficients, maybe this will become a dict in the future.)

I hope this helps!

Best regards
Johannes

**Comment by Chris-A13** [comment]
Thank you @joha2 ,

I can absolutely share my thesis link with you to help recognise the work your module has done for me. If I can get it to work, it will be a saving grace.

Ok perfect, I am really glad that I have found this module. It will save me reinventing the wheel and I can focus on the other aspects of the software package. Thank you for giving me the link for the demo file for using matplotlib. I will have to try and get that to work so that I can visual my coordinate system when creating the mirror system.

I have started diving into the code for the surface shapes and I can definitely see how many options their are for the shape design. Thank you  very much.

Your response is great and has been very helpful.

Do you by chance, happen to know if their is a way with your module to find the coordinates that the ray being traced will end up. I am just currently creating basic systems and I'm wanting to check that the output is where it should be so I know that I've done it correctly?

Thank you again for any help available.
Chris

**Comment by joha2** [comment]
Hey @Chris-A13 

You're welcome! Glad that my comment was helpful. Unfortunately, our documentation is not that good at some points, therefore the issues here are also a very valuable source of information. Perhaps also the wiki main page with its FAQ can help at some points.

For the drawing: We tried to simplify this task as possible. Usually, you only have to call `draw(opticalsystem, rays)` maybe with an `interactive=True` keyword argument. Just play with the demo I mentioned and it should become more clear.

The ray intersection points are accessible via the RayPath object. This consists of a list of RayBundle objects, which have properties `x`, `k`, `Efield`. The `x` contain the intersection points at the appropriate surface, see my response in #140 . It is a numpy array with three indices. The first one is the number of intersection between the last surface and the actual surface (so 0 is the starting point of the ray bundle and -1 is the end point, which corresponds to the intersection point at the actual surface). The second one is 0, 1, 2 for x, y, z. The third one is the number of the ray to be considered, where 0 is the chiefray.

I hope this helps to clarify this a bit. If you have further questions, please just ask :-)

Best wishes
Johannes

**Comment by Chris-A13** [comment]
Your solution worked perfectly, once I threw a round function on the print, I can see why their is the comment in the aim module about it not producing perfect results as I'm not sure why my ray which should have hit coord 30 apparently hit 29.999999993 haha.

Is there a way to limit the size of the mirrors so that if the ray does not hit the mirror, it wont be reflected back from an invisible point. I've noticed in some of the demos (demo.mirrors for one) that the light misses the mirror but it is still reflected off a point where an extension to the mirror would lay, if that makes sense.

I'll attach a picture showing what I mean as I don't think I worded that super well.
![Demo_Mirrors](https://user-images.githubusercontent.com/68369273/89600111-63442a00-d8a0-11ea-953b-53690770500d.png)
The circled section shows the rays going beyond the mirror and the bracketed section shows the rays moving below the mirror but still being reflected.

**Comment by joha2** [comment]
Dear @Chris-A13 

the 30.0 vs 29.99999999 I think is a pecularity of Python, internally these numbers are identical (at least in double accuracy). For your question of reducing size of a mirror: For this you want to use apertures, which can be introduced by the `aperture=` keyword argument in the `Surface.p(...)` call. At the moment you only have access to rectangular and circular apertures, but there are more to follow.

Hope this helps!

**Comment by Chris-A13** [comment]
Dear @joha2 ,

Your solutions make me so happy haha. I was wondering if you could make a suggestion on a potential way to almost pass an 'image' of just black and white squares as an input to run through the system to find out where they will end up at the end and if there is any 'bleeding' of light at the white/black intersections.

**Comment by Chris-A13** [comment]
Dear @joha2 

I hope your week has gone smoothly.
I was just wondering if you had been able to give any thought into if an off axis parabolic mirror would be able to be incorporated into the code. 
I am currently working out my surface equations and I was going to try and use the FreeShape class in the surface_shape library to create this mirror. But if you don't think that it is achievable, I will look at attempting to get such a complex mirror into the system in a different way.

Thanks for the help,
Chris

**Comment by joha2** [comment]
Dear @Chris-A13 

sorry I totally forgot to answer your last questions. For the first one, unfortunately there is no standard way in doing what you want. I would suggest to create a user defined grid of rays whereas in the "white" pixels there may start several rays with different directions (of course only the ones not stopped by the STOP) and in the "black" areas there start no rays. If the pixel size is sufficiently small, these just represent different field points with a bundle for every each of them. In the image you have to perform some kind of binning to sum up all rays hitting in the respective fields and decide whether the intensity degrades.

For the off-axis paraboloid I would suggest using the Conic class with a conic constant -1. The curvature radius depends with a factor 2 on the focal length. The only thing to consider is that the aperture is circular, but should not be on center. You have to incorporate a certain decenter in x or y (in your case 50.8 mm if I understood the drawing correctly. The diameter of the mirror is also 50.8 mm.

Hope this helps!

Best regards
Johannes

**Comment by Chris-A13** [comment]
Thank you for you help @joha2 

I have been focusing on making the 3D shape using your suggestion. You said to use -1 as the cc but in the conic class in surface_shape, a cc of -1 is commented to be a oblate rotational ellipsoid where as a cc of 1 is said to be a rotational paraboloid. I was just wondering if the coding comments was out of date?

Thank you for your help, your insight helps so much more than you can imagine.
Have a great weekend,
Chris

**Comment by joha2** [comment]
Hey @Chris-A13 thanks for pointing this out. This is definitely wrong in our documentation. Since the square root in the denominator of the conic only becomes one when 1 + cc = 0. Therefore cc = -1 for a paraboloid. We will change that immediately!

Best wishes and have also a nice weekend
Johannes

**Comment by Chris-A13** [comment]
Hey @joha2 

I have been putting in a spherical mirror into a basic 1 mirror system and plotting the focal point.
The spherical mirror has a radius of 38mm so im plotting the coordinate at (zcoord-19) since that is where the focal point should be.
I'm not sure how the Curv works though as all the examples are always 1/something and I appear to get the highest density of focal point around 1/42.8 which I found through trial and error.
I was just wondering if there is some special calculation required for the Curv in the conic or if I am missing something.

Also, is it safe to assume that there is no spherical aberration in the code as I'm hoping to keep the system as an 'ideal' case.

Thank you for your ongoing support,
Regards,
Chris

**Comment by joha2** [comment]
Hey @Chris-A13 

The curvature parameter is strictly curv = 1/CurvatureRadius. Therefore, no special calculation is needed.

About spherical aberration: Aberrations are only neglected in the paraxial case (small angles, small ray heights). But our code calculates without any approximations (except the geometrical wave approximation), such that there are indeed spherical aberrations.

See for example the following system
````Python
>>> from pyrateoptics import build_rotationally_symmetric_optical_system
>>> from pyrateoptics import draw, raytrace
>>> from pyrateoptics.sampling2d.raster import MeridionalFan
>>> components = [(0, 0, 0, None, "obj", {}), (-38, 0, 100, None, "mirror", {"is_mirror": True}), (0, 0, -19, None, "img", {})]
>>> (s, seq) = build_rotationally_symmetric_optical_system(components)
>>> r = raytrace(s, seq, 11, {"radius": 19, "raster":MeridionalFan()})
>>> draw(s, r)
````

which is obtained from your description, and where you can see massive spherical aberrations in the focal point.

![Figure_1](https://user-images.githubusercontent.com/12564815/94281320-c53f1880-ff4e-11ea-9e1f-904e5042cfee.png)

I hope this clarifies these issues a bit.

Best wishes
Johannes

**Comment by joha2** [comment]
I just close this for reducing the open issues. If you have further questions, just continue to write here.
