### ISSUE TITLE
python setup.py build followed by python setup.py install does not generate adjectives.json and nouns.json

### ISSUE THREAD

**Issue by ivoihrke** [mess42/pyrate#159]
This is a bit irritating when starting to develop for pyrate using the git-repo. Locations are 

pyrateoptics/core/names/adjectives.json
pyrateoptics/core/names/nouns.json

I fixed it on my side by generating fake files (or maybe downloading them somewhere) and manually copying them into 
the conda environments' pyrate package directory.

I suggest building/downloading them automatically and including them in the 

python setup.py install 

file list.

**Comment by joha2** [comment]
@ivoihrke thanks for pointing this out. I think I actually forgot to add them to the setup file. I will change this as soon as possible.

**Comment by joha2** [comment]
@ivoihrke this should be solved now with the last PR merged. Please test whether this works for you.

Best wishes
Johannes
