### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by theinze** [mess42/pyrate#19]
I've tried to run `demo_effl.py` and `demo_loadsave.py` but get the following error:

``` python
Traceback (most recent call last):
  File "demo_effl.py", line 69, in <module>
    s = OpticalSystem(objectDistance = 0.0)
TypeError: __init__() got an unexpected keyword argument 'objectDistance'
```

I have an Ubuntu machine, with Python 2.7.6, numpy 1.8.2, scipy 0.13.3, matplotlib 1.3.1 running ...

**Comment by joha2** [comment]
Yes this is indeed a bug and comes from our refactorization of the local coordinate systems and therefore a change in the OpticalSystem constructor.

**Comment by mess42** [comment]
Dear theinze,

thank you very much for your interest in pyrate. You are very welcome to
join.

Did joha2 fix this bug to your appreciation ?

Did joha2 already tell you about the basic concept of pyrate ? Some of
it is depicted in the folder rtfm, but I'm sure you will have questions.

Please do not hesitate to ask us for an introductory tour or any
specific questions.

**Comment by joha2** [comment]
With pull request #20 demos are operational again. Therefore fixed. :-)
