### ISSUE TITLE
Ray aiming

### ISSUE THREAD

**Issue by joha2** [mess42/pyrate#29]
Ray aiming seems to be broken:
![pyrate_gui_stop_error](https://cloud.githubusercontent.com/assets/12564815/21287187/162a8a9a-c466-11e6-8715-64f2d6a310a4.png)
* STOP: Surface 5
* Aiming: Stop Diameter
* All rays should hit surface 5 at the same z position

**Comment by mess42** [comment]
solved in commit  4e0022f
