### ISSUE TITLE
Freecad Addon manager integration

### ISSUE THREAD

**Issue by HoWilgh** [mess42/pyrate#39]
Hello,

Nice piece of work... at least from the screenshots =).
Could you please make this available through the built in Freecad- Addon-manager?

This would help users installing this macro and you to find users!

BR,
HoWil

**Comment by HoWilgh** [comment]
Please see https://github.com/FreeCAD/FreeCAD-addons

**Comment by joha2** [comment]
Thanks for the hint. It's added.
