### ISSUE TITLE
K vector separated from wave number

### ISSUE THREAD

**Issue by joha2** [mess42/pyrate#64]
Consider the determinant

![equation](http://latex.codecogs.com/gif.latex?%5Cdet%28-k%5E2%20%5Cdelta_%7Bij%7D%20%2B%20k_i%20k_j%20%2B%20k_0%5E2%20%5Cvarepsilon_%7Bij%7D%29%20%3D%200)

where

![equation](http://latex.codecogs.com/gif.latex?k_0%20%3D%20%5Cfrac%7B2%5Cpi%7D%7B%5Clambda%7D)

Then we may separate k_0 from the k vectors. Does this lead to any difficulties in raytracing?

The advantages are:

* k vector components are complex and of order 1
* we reduce the problems of large*small has very much numerical errors
* we may reduce the material code (since at the moment Knorm and K functions are nearly doubled)
* and we may insert lambda at the very end of the calculation

**Comment by mess42** [comment]
i like this idea.
the unit systems should be well documented in the comments
